name: Build and Export Unsigned iOS App

on:
  push:
    branches:
      - master  # Trigger build on push to master branch
  pull_request:
    branches:
      - master  # Trigger build on pull request to master branch

jobs:
  build:
    runs-on: macos-latest  # Use macOS runner for iOS build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Fetch repository code

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'  # Set Node.js version for React Native

    - name: Install Dependencies & Clean Cache
      run: |
        npm install  # Install npm dependencies
        npx react-native link  # Ensure libraries are linked
        rm -rf ~/Library/Developer/Xcode/DerivedData  # Clean Xcode cache
        cd ios
        pod deintegrate  # Remove old dependencies
        rm -rf Pods Podfile.lock  # Delete CocoaPods cache
        pod install --repo-update --verbose  # Reinstall dependencies

    - name: Build iOS App (Release) Without Code Signing
      run: |
        xcodebuild clean archive \
          -project ios/MyReactNativeApp.xcodeproj \
          -scheme MyReactNativeApp \
          -sdk iphoneos \
          -configuration Release \
          -archivePath build/MyReactNativeApp.xcarchive \
          CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY=""

    - name: Export .ipa Without Signing
      run: |
        xcodebuild -exportArchive \
          -archivePath build/MyReactNativeApp.xcarchive \
          -exportPath build \
          -exportOptionsPlist ios/exportOptions.plist \
          CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY=""
        
        # Debug: List build files
        ls -lh build

    - name: Upload .ipa as artifact
      uses: actions/upload-artifact@main
      with:
        name: ios-unsigned-app
        path: build/*.ipa  # Upload generated .ipa file
