name: Build and Export Unsigned iOS App

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install Dependencies & Clean Cache
      run: |
        npm install
        rm -rf ~/Library/Developer/Xcode/DerivedData  # Clean Xcode cache
        cd ios
        pod deintegrate
        rm -rf Pods Podfile.lock
        pod install --repo-update --verbose  # Ensure dependencies are fresh

    - name: Build iOS App (Release) Without Code Signing
      run: |
        xcodebuild clean archive \
          -project ios/MyReactNativeApp.xcodeproj \
          -scheme MyReactNativeApp \
          -sdk iphoneos \
          -configuration Release \
          -archivePath build/MyReactNativeApp.xcarchive \
          CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY=""

    - name: Export .ipa Without Signing
      run: |
        xcodebuild -exportArchive \
          -archivePath build/MyReactNativeApp.xcarchive \
          -exportPath build \
          -exportOptionsPlist ios/exportOptions.plist \
          CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY=""
        
        # Debug: List build files
        ls -lh build

    - name: Upload .ipa as artifact
      uses: actions/upload-artifact@main
      with:
        name: ios-unsigned-app
        path: build/*.ipa
